blank_issues_enabled: false
contact_links:
  - name: "Documentation & FAQ"
    url: "https://docs.openappsec.io/"
    about: "Check the documentation before submitting an issue."
  - name: "Feature Requests & Discussions"
    url: "https://github.com/openappsec/discussions"
    about: "Please open a discussion for feature requests, or create an issue if necessary."
